language: nix

script: nix-build --attr proto3-suite-linux --arg enableDhall true release.nix

## Caching: https://github.com/travis-ci/travis-ci/issues/6604
sudo: required

before_cache: |
  sudo nix-collect-garbage --delete-older-than 7d --dry-run

cache:
  directories:
    - /nix
