language: nix

script: nix-build --attr proto3-suite-linux --arg enableDhall true release.nix

## Caching: https://github.com/travis-ci/travis-ci/issues/6604
sudo: required

install: |
  if [ -d ~/nix-cache ]
  then
    sudo rm -rf -- /nix/*
    (cd ~/nix-cache && tar c -f - .) | (cd /nix && sudo tar x -k -f - 2> /dev/null || true)
  fi

before_cache: |
  sudo nix-collect-garbage --delete-older-than 7d --dry-run
  sudo rm -rf ~/nix-cache
  mkdir ~/nix-cache
  (cd ~/nix && tar c -f - .) | (cd ~/nix-cache && tar x -f -)

cache:
  directories:
    - ~/nix-cache
