language: nix

script: |
  DERIVATION=$(nix-instantiate --attr proto3-suite-linux --arg enableDhall true release.nix)
  nix-env --set "${DERIVATION}" --profile buildDependencies
  nix-store --realise "${DERIVATION}"

## Caching: https://github.com/travis-ci/travis-ci/issues/6604
## But we deviate from that advice by caching "/nix" directly.
## We collect garbage to avoid the cache growing indefinitely.

sudo: required

## before_cache: |
##   nix-collect-garbage --delete-older-than 7d

cache:
  directories:
    - /nix
