language: nix

script: |
  echo "======== Building dependencies"
  DERIVATION=$(nix-instantiate --attr proto3-suite --arg enableDhall true release.nix)
  ln -s "${DERIVATION}" /nix/var/nix/gcroots/buildDependencies
  echo "======== Building proto3-suite as such"
  nix-store --realise "${DERIVATION}"

## Caching: https://github.com/travis-ci/travis-ci/issues/6604
## But we deviate from that advice by caching "/nix" directly.
## We collect garbage to avoid the cache growing indefinitely.

sudo: required

before_cache: |
  nix-store --gc --option keep-outputs true

cache:
  directories:
    - /nix
