language: nix

script: nix-build --attr proto3-suite-linux --arg enableDhall true release.nix

## Caching: https://github.com/travis-ci/travis-ci/issues/6604
sudo: required

install: |
  if [ -e ~/nix-cache ]; then
    sudo rm -rf /nix/*
    cp -a ~/nix-cache/* /nix
  fi

before_cache: |
  if [ ! -e ~/nix-cache ]; then
    cp -a /nix/* ~/nix-cache
  fi

cache:
  directories:
    - $HOME/nix-cache
