language: nix

script: nix-build --attr proto3-suite-linux --arg enableDhall true release.nix

## Caching: https://github.com/travis-ci/travis-ci/issues/6604
sudo: required

install: |
  if [ -d ~/nix-cache ]
  then
    cp -a ~/nix-cache/. /nix
  fi

before_cache: |
  nix-collect-garbage --delete-older-than 7d --dry-run
  rm -rf ~/nix-cache
  cp -a /nix/. ~/nix-cache

cache:
  directories:
    - ~/nix-cache
