language: nix

script: |
  set -x
  DERIVATION=$(nix-instantiate --attr proto3-suite-linux --arg enableDhall true release.nix)
  ln -s "${DERIVATION}" /nix/var/nix/gcroots/buildDependencies
  echo "1==============================="
  nix-store --gc --print-roots
  echo "1-------------------------------"
  nix-store --realise "${DERIVATION}"
  echo "2==============================="
  nix-store --gc --print-roots
  echo "2-------------------------------"

## Caching: https://github.com/travis-ci/travis-ci/issues/6604
## But we deviate from that advice by caching "/nix" directly.
## We collect garbage to avoid the cache growing indefinitely.

sudo: required

before_cache: |
  echo "3==============================="
  nix-store --gc --print-roots
  echo "3-------------------------------"

## nix-collect-garbage --delete-older-than 7d

cache:
  directories:
    - /nix
