resolver: lts-7.4

packages:
- .
- location:
    git: https://github.com/awakenetworks/proto3-wire.git
    commit: a938330bf794cf3fa05591d03906915df98d157c
  extra-dep: true

extra-deps: [ aeson-1.1.1.0
            , neat-interpolation-0.3.2.1
            , optparse-applicative-0.13.2.0
            , optparse-generic-1.2.1
            , turtle-1.3.6
            ]
