resolver: lts-7.4

packages:
- .
- location:
    git: https://github.com/awakenetworks/proto3-wire.git
    commit: 4f355bbac895d577d8a28f567ab4380f042ccc24
  extra-dep: true

extra-deps: [ aeson-1.1.1.0
            , aeson-pretty-0.8.2
            , cabal-doctest-1.0.2
            , insert-ordered-containers-0.2.1.0
            , neat-interpolation-0.3.2.1
            , optparse-applicative-0.13.2.0
            , optparse-generic-1.2.1
            , swagger2-2.1.6
            , turtle-1.3.6
            ]
