resolver: lts-11.0

packages:
- .
- location:
    git: https://github.com/joshvera/proto3-wire.git
    commit: c8792bc33154e849239b1c91ffe06af2e765d734
  extra-dep: true

extra-deps: [ aeson-pretty-0.8.5
            , cabal-doctest-1.0.2
            , insert-ordered-containers-0.2.1.0
            , neat-interpolation-0.3.2.1
            , optparse-applicative-0.14.2.0
            , optparse-generic-1.3.0
            , swagger2-2.1.6
            , aeson-1.3.1.1
            ]
