resolver: lts-7.4

packages:
- .
- location:
    git: https://github.com/awakenetworks/proto3-wire.git
    commit: 1e09c1f4cdc953cc6748891f669f0be96f14e5b8 
  extra-dep: true

extra-deps: [ aeson-1.1.1.0
            , neat-interpolation-0.3.2.1
            , optparse-applicative-0.13.2.0
            , optparse-generic-1.2.1
            , turtle-1.3.6
            ]
