name: ci
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        name: Checkout
      - uses: cachix/install-nix-action@v13
        name: Install Nix
      - uses: cachix/cachix-action@v10
        name: Set up Cachix
        with:
          name: awakesecurity
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-build --arg enableDhall true
